name: b2-ubuntu
channels:
  - conda-forge
  - nodefaults
dependencies:
  - gxx==15.3.0
  - numpy
  - gmp
  - mpfr
  - mpc
  - auditwheel
  - automake
  - autoconf
  - libtool
  - libboost
  - eigen
  - eigenpy
  - libboost-python
  - scipy
  - wheel
  - python-build
  - patchelf
