#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Bertini 2 documentation build configuration file, created by
# sphinx-quickstart on Wed Oct  4 23:28:46 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# stuff to get autodoc to work. silviana amethyst
import sys
import os

# autodoc needs to import the `bertini` package so it can introspect classes
# and functions. Prefer the installed package (pip install / virtualenv) so
# the C++ binary extension `_pybertini` resolves correctly.
#
# Only add the source tree at python/ to sys.path if it has the compiled
# `_pybertini` next to it. Otherwise it shadows the installed package and
# autodoc silently produces empty stubs (the source `__init__.py` re-exports
# from `bertini._pybertini`, which lives in the .so file).
#
# For local development, set PYTHONPATH (or BERTINI_BUILD_DIR) to your CMake
# build's python_bindings/ directory if it isn't an installed package.
import glob
def _has_pybertini(path):
    return bool(glob.glob(os.path.join(path, 'bertini', '_pybertini*.so'))) or \
           bool(glob.glob(os.path.join(path, 'bertini', '_pybertini*.pyd')))

_local_src = os.path.abspath('../')           # repo's python/ (source tree)
_local_bld = os.path.abspath('../../../bld/python_bindings')

for _p in (_local_bld, _local_src):
    if _has_pybertini(_p):
        sys.path.insert(0, _p)

# Allow an explicit override (used by maintainers with non-standard layouts).
_override = os.environ.get('BERTINI_BUILD_DIR')
if _override and _has_pybertini(_override):
    sys.path.insert(0, _override)

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.githubpages',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinxcontrib.bibtex',
    'sphinx_rtd_theme'
    ]

autosectionlabel_prefix_document = True

bibtex_bibfiles = ['../../../doc_resources/bertini2.bib']

#    'sphinx.ext.autosectionlabel_prefix_document',
#autodoc_default_flags = ['members', 'undoc-members','show-inheritance'] 
#, 'special-members'
#, , 'inherited-members'

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# see http://www.sphinx-doc.org/en/stable/ext/autodoc.html#confval-autoclass_content
autoclass_content = 'both'

toc_object_entries_show_parents = 'hide'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Bertini'
copyright = '2015-2025, Bertini Team'
author = 'Bertini Team'


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents. Prefer CI-supplied env vars (set by .github/workflows/docs.yml)
# since they work on shallow clones; fall back to gitpython for local builds.
last_commit = os.environ.get('BERTINI_GIT_SHA')
if last_commit:
    version = last_commit[:7]
    release = last_commit
else:
    try:
        import git  # package gitpython
        repo = git.Repo(search_parent_directories=True)
        last_commit = str(repo.head.commit)
        version = last_commit[:7]
        release = last_commit
    except Exception:
        last_commit = 'unknown'
        version = last_commit
        release = version

build_date = os.environ.get('BERTINI_BUILD_DATE', '')
if build_date:
    # sphinx_rtd_theme shows `release` in the sidebar header; appending the
    # build date there makes it visible without template overrides.
    release = '{} ({})'.format(version, build_date)

# Expose build metadata to Jinja templates (used by _templates/footer.html
# to render the "Built from <sha> on <date>" line in the page footer).
html_context = {
    'commit_sha': last_commit if last_commit and last_commit != 'unknown' else '',
    'commit_short': version if last_commit and last_commit != 'unknown' else '',
    'build_date': build_date,
}




# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['test']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# This tells Sphinx to include your custom CSS file
html_css_files = [
    'custom.css',  # This is the filename, not the full path
]


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Bertinidoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Bertini.tex', 'Bertini 2 Python Documentation',
     'Bertini Team', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'bertini', 'Bertini 2 Python Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Bertini 2', 'Bertini 2 Python Documentation',
     author, 'Bertini', 'Software for Numerical Algebraic Geometry.',
     'Miscellaneous'),
]



html_logo = "images/bpy_icon_.svg"

