/* confdefs.h */
#define PACKAGE_NAME "b2"
#define PACKAGE_TARNAME "b2"
#define PACKAGE_VERSION "2.0.1"
#define PACKAGE_STRING "b2 2.0.1"
#define PACKAGE_BUGREPORT "danielthebrake@gmail.com"
#define PACKAGE_URL "http://github.com/bertiniteam/b2"
#define PACKAGE "b2"
#define VERSION "2.0.1"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_EIGEN3_EIGEN_DENSE 1
#define HAVE_BOOST /**/
#define HAVE_BOOST_SYSTEM /**/
#define HAVE_BOOST_FILESYSTEM /**/
#define HAVE_BOOST_CHRONO /**/
#define HAVE_BOOST_REGEX /**/
#define HAVE_BOOST_TIMER /**/
#define HAVE_BOOST_UNIT_TEST_FRAMEWORK /**/
#define HAVE_BOOST_SERIALIZATION /**/
#define HAVE_BOOST_PROGRAM_OPTIONS /**/
#define HAVE_BOOST_LOG /**/
#define HAVE_BOOST_LOG_SETUP /**/
#define HAVE_BOOST_THREAD /**/
