# Generates the producer-info header (git commit of the build) at BUILD time, so run
# records can say which exact source produced them.  Runs on every build via a custom
# target; writes the file only when the content changes, so no rebuild churn.
#
# Expects: -DSRC_DIR=<repo root> -DOUT_FILE=<path to generated header>

find_package(Git QUIET)

set(commit "unknown")
if(GIT_FOUND AND EXISTS "${SRC_DIR}/.git")
	execute_process(
		COMMAND "${GIT_EXECUTABLE}" -C "${SRC_DIR}" rev-parse HEAD
		OUTPUT_VARIABLE commit_raw
		OUTPUT_STRIP_TRAILING_WHITESPACE
		ERROR_QUIET
		RESULT_VARIABLE git_result)
	if(git_result EQUAL 0)
		set(commit "${commit_raw}")
		# a dirty tree is not that commit; say so honestly
		execute_process(
			COMMAND "${GIT_EXECUTABLE}" -C "${SRC_DIR}" diff-index --quiet HEAD --
			RESULT_VARIABLE dirty_result
			ERROR_QUIET)
		if(NOT dirty_result EQUAL 0)
			set(commit "${commit}-dirty")
		endif()
	endif()
endif()

set(content "// generated by cmake/GenerateProducerInfo.cmake -- do not edit, do not commit
#pragma once
#define BERTINI2_GIT_COMMIT \"${commit}\"
")

if(EXISTS "${OUT_FILE}")
	file(READ "${OUT_FILE}" existing)
else()
	set(existing "")
endif()
if(NOT content STREQUAL existing)
	file(WRITE "${OUT_FILE}" "${content}")
endif()
