name: Sync to MPI GitLab
on: 
  push
jobs:
  sync:
    if: github.repository == 'bertiniteam/b2' #only on official 
    runs-on: ubuntu-latest
    steps:
    - name: Sync to GitLab
      # You may pin to the exact commit or the version.
      # uses: kujov/gitlab-sync@b19399d43e81ac88acb6eefd5588e6ebde3d7d88
      uses: kujov/gitlab-sync@2.2.1
      with:
        # The URL of the GitLab repository (e.g., https://gitlab.com/user/repo.git)
        gitlab_url: ${{ secrets.GITLAB_URL }}
        # Your GitLab username
        username: ${{ secrets.GITLAB_USERNAME }}
        # Your GitLab Personal Access Token with required permissions
        gitlab_pat: ${{ secrets.GITLAB_PAT }}
        # Whether to force push to GitLab. Defaults to false.
        
        force_push: true # optional, default is false
